### PR TITLE
Support phabricator urls with https

### PR DESCRIPTION
**Pull request by seanabraham**
This PR will add support for Phabricator URLs of the form "phabricator.example.com" as before but also "http://phabricator.example.com" and "https://phabricator.example.com". My current phabricator setup was not responding to `api/harbormaster.sendmessage` calls as it was just returning 301s, redirecting the `http` calls to `https`. Let me know if you'd like me to do this in a different way. Also sorry for some of the whitespace changes, my IDE automatically made those changes, let me know if you'd like me to revert. 

Also, I haven't been able to test this because I don't exactly know how to build the teamcity plugin zip from source. Could you add instructions maybe? Happy to test in depth after I figure that out.

### CODE REVIEW

**Comment by SeanA208** [comment]
And I know the URI parsing is a bit repetitive here but I wasn't sure where a convenient place for a util class would be. Let me know if you want me to create a common location for some shared code or if you're alright leaving this as is.

**Comment by seanabraham** [comment]
Ah I see, building is as simple as running `mvn package`. I tested this on my TeamCity / Phabricator instances and it worked as expected with an `https` Phabricator url

**Comment by seanabraham** [comment]
cc @halojedi20

**Comment by halfmatthalfcat** [comment]
Oh, legit. I'll pull it down and give it a run this weekend.

**Comment by seanabraham** [comment]
Any luck @halojedi20? I think I'll have another PR incoming for doing something similar on the harbormaster side, i.e. support a TeamCity server behind https.

**Comment by halfmatthalfcat** [comment]
I got the travis yml integrated but for some reason the build was failing, something to do with the travis configuration but I haven't had time to look into it. Just pulled your pr down though and looks good! Thanks for contributing!

**Pull request merged**
